image: Visual Studio 2017

environment:
  CMAKE_ARGS: '-G "NMake Makefiles JOM" -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo'
  matrix:
  - QTDIR: C:\Qt\5.13\msvc2017_64
    VCVARS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat"
    PLATFORM:
  - QTDIR: C:\Qt\5.13\msvc2017
    VCVARS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\vcvars32.bat"
    PLATFORM: x86

init:
- call "%QTDIR%\bin\qtenv2.bat"
- set PATH=C:\Qt\Tools\QtCreator\bin;%PATH%
- call "%VCVARS%" %PLATFORM%
- cd /D "%APPVEYOR_BUILD_FOLDER%"

before_build:
- git submodule update --init --recursive
- git clone https://gitlab.matrix.org/matrix-org/olm.git
- cmake %CMAKE_ARGS% -Holm -Bbuild/olm
- cmake --build build/olm

build_script:
- cmake %CMAKE_ARGS% -H. -Bbuild "-DOlm_DIR=build/olm"
- cmake --build build
# qmake uses olm just built by CMake - it can't build olm on its own.
- qmake "INCLUDEPATH += olm/include" "LIBS += -Lbuild" "LIBS += -Lbuild/olm" && jom

#after_build:
#- cmake --build build --target install
#- 7z a quotient.zip "%DEPLOY_DIR%\"

# Uncomment this to connect to the AppVeyor build worker
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

test: off

#artifacts:
#- path: quotient.zip
