language: cpp

matrix:
  include:
    - { os: linux, dist: trusty, compiler: gcc }
    - { os: linux, dist: trusty, compiler: clang }
    - os: osx

install:
 - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; else sudo apt-get update -qq; fi
 - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install qt5; export PATH="$PATH:/usr/local/opt/qt/bin"; else sudo apt-get install -y qt5-default; fi
 - git clone https://github.com/matrix.org/matrix-doc
 - git clone https://github.com/KitsuneRal/api-generator
 - cd api-generator && mkdir build && cd build && cmake .. && cmake --target all

before_script:
 - mkdir build && cd build
 - cmake -DMATRIX_DOC_PATH="matrix-doc" -DAPIGEN_PATH="api-generator/build/api-generator" ..

script: cmake --build . --target all

notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGtpdHN1bmUlM0FtYXRyaXgub3JnLyUyMVBDelV0eHRPalV5U3hTZWxvZiUzQW1hdHJpeC5vcmc"
        on_success: change  # always|never|change
        on_failure: always
        on_start: never
