name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [ubuntu-18.04, macos-10.15]
#        e2ee: [false, true]
        compilers: [ 'CC=gcc CXX=g++', 'CC=clang CXX=clang++']
        exclude:
        - os: macos-10.15
          compilers: 'CC=gcc CXX=g++'

    steps:
    - uses: actions/checkout@v2

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v2
      with:
        path: ${{runner.workspace}}/Qt
        key: ${{ runner.os }}-QtCache

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.11.1
      with:
        version: '5.9.9'
#        dir: ${{runner.home}}
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      run: |
        export ${{matrix.compilers}}
        cmake -Bbuild -S$GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_SHARED_LIBS=$BUILD_SHARED_LIBS

    - name: Build
      run: cmake --build build --target quotest

#    - name: Test
#      working-directory: ${{runner.workspace}}/build
#      run: quotest ...
